### ISSUE TITLE
Unable to follow C code example, cannot generate azure_iot_sdks.sln

### ISSUE THREAD

**Issue by peterso** [iot-for-all/iot-central-high-availability-clients#3]
Hello, I am trying to follow your C code example without success. https://github.com/iot-for-all/iot-central-high-availability-clients/tree/main/C

I am stuck on the proper cmake command. I had to enable the cmake option "use_prov_client" with cmake-gui for the azure-iot-sdk-c/provisioning_client/samples/iot_central_failover_sample/ dir to appear. 
I am running on MacOS Big Sur and have followed the instructions for my devbox: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#macos

$ cd azure-iot-sdk-c/cmake
$ cmake .. -G "Visual Studio 16 2019"

returns the following result:
```
CMake Error: Could not create named generator Visual Studio 16 2019

Generators
* Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  Xcode                        = Generate Xcode project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
```

**Comment by firedog1024** [comment]
Unfortunately I have not tried this on MacOS and the instructions were designed for use with Windows with Visual Studio development tools.  I would suggest following the instructions for using the Azure IoT SDK with MacOS [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#macos).  This should enable you to build the samples then it should be pretty straight forward to integrate this sample in
